package com.huawei.vas.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Oct 24 20:51:03 CST 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://service.vas.huawei.com", name = "VASService")
@XmlSeeAlso({ObjectFactory.class, com.huawei.vas.bean.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VASService {

    @WebResult(name = "serviceOrderResponse", targetNamespace = "http://service.vas.huawei.com", partName = "serviceOrderResponse")
    @WebMethod
    public com.huawei.vas.bean.ServiceOrderResp serviceOrder(
        @WebParam(partName = "serviceOrderReq", name = "serviceOrderReq", targetNamespace = "http://service.vas.huawei.com")
        com.huawei.vas.bean.ServiceOrderReq serviceOrderReq
    );

    @WebResult(name = "userTokenUpdateResponse", targetNamespace = "http://service.vas.huawei.com", partName = "userTokenUpdateResponse")
    @WebMethod
    public com.huawei.vas.bean.UserTokenUpdateResp userTokenUpdate(
        @WebParam(partName = "userTokenUpdateReq", name = "userTokenUpdateReq", targetNamespace = "http://service.vas.huawei.com")
        com.huawei.vas.bean.UserTokenUpdateReq userTokenUpdateReq
    );

    @WebResult(name = "serviceAuthResponse", targetNamespace = "http://service.vas.huawei.com", partName = "serviceAuthResponse")
    @WebMethod
    public com.huawei.vas.bean.ServiceAuthResp serviceAuth(
        @WebParam(partName = "serviceAuthReq", name = "serviceAuthReq", targetNamespace = "http://service.vas.huawei.com")
        com.huawei.vas.bean.ServiceAuthReq serviceAuthReq
    );

    @WebResult(name = "userAuthResponse", targetNamespace = "http://service.vas.huawei.com", partName = "userAuthResponse")
    @WebMethod
    public com.huawei.vas.bean.UserAuthResp userAuth(
        @WebParam(partName = "userAuthReq", name = "userAuthReq", targetNamespace = "http://service.vas.huawei.com")
        com.huawei.vas.bean.UserAuthReq userAuthReq
    );

    @WebResult(name = "productServiceDetailQueryResponse", targetNamespace = "http://service.vas.huawei.com", partName = "productServiceDetailQueryResponse")
    @WebMethod
    public com.huawei.vas.bean.ProductServiceDetailQueryResp productServiceDetailQuery(
        @WebParam(partName = "productServiceDetailQueryReq", name = "productServiceDetailQueryReq", targetNamespace = "http://service.vas.huawei.com")
        com.huawei.vas.bean.ProductServiceDetailQueryReq productServiceDetailQueryReq
    );

    @WebResult(name = "prodDetailQueryResponse", targetNamespace = "http://service.vas.huawei.com", partName = "prodDetailQueryResponse")
    @WebMethod
    public com.huawei.vas.bean.ProdDetailQueryResp prodDetailQuery(
        @WebParam(partName = "prodDetailQueryReq", name = "prodDetailQueryReq", targetNamespace = "http://service.vas.huawei.com")
        com.huawei.vas.bean.ProdDetailQueryReq prodDetailQueryReq
    );

    @WebResult(name = "serviceDetailQueryResponse", targetNamespace = "http://service.vas.huawei.com", partName = "serviceDetailQueryResponse")
    @WebMethod
    public com.huawei.vas.bean.ServiceDetailQueryResp serviceDetailQuery(
        @WebParam(partName = "serviceDetailQueryReq", name = "serviceDetailQueryReq", targetNamespace = "http://service.vas.huawei.com")
        com.huawei.vas.bean.ServiceDetailQueryReq serviceDetailQueryReq
    );
}
