
package com.huawei.vas.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Oct 24 20:51:03 CST 2011
 * Generated source version: 2.2.9
 * 
 */

public final class VASService_VASService_Client {

    private static final QName SERVICE_NAME = new QName("http://service.vas.huawei.com", "VASServiceService");

    private VASService_VASService_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = VASServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        VASServiceService ss = new VASServiceService(wsdlURL, SERVICE_NAME);
        VASService port = ss.getVASService();  
        
        {
        System.out.println("Invoking serviceOrder...");
        com.huawei.vas.bean.ServiceOrderReq _serviceOrder_serviceOrderReq = null;
        com.huawei.vas.bean.ServiceOrderResp _serviceOrder__return = port.serviceOrder(_serviceOrder_serviceOrderReq);
        System.out.println("serviceOrder.result=" + _serviceOrder__return);


        }
        {
        System.out.println("Invoking userTokenUpdate...");
        com.huawei.vas.bean.UserTokenUpdateReq _userTokenUpdate_userTokenUpdateReq = null;
        com.huawei.vas.bean.UserTokenUpdateResp _userTokenUpdate__return = port.userTokenUpdate(_userTokenUpdate_userTokenUpdateReq);
        System.out.println("userTokenUpdate.result=" + _userTokenUpdate__return);


        }
        {
        System.out.println("Invoking serviceAuth...");
        com.huawei.vas.bean.ServiceAuthReq _serviceAuth_serviceAuthReq = null;
        com.huawei.vas.bean.ServiceAuthResp _serviceAuth__return = port.serviceAuth(_serviceAuth_serviceAuthReq);
        System.out.println("serviceAuth.result=" + _serviceAuth__return);


        }
        {
        System.out.println("Invoking userAuth...");
        com.huawei.vas.bean.UserAuthReq _userAuth_userAuthReq = null;
        com.huawei.vas.bean.UserAuthResp _userAuth__return = port.userAuth(_userAuth_userAuthReq);
        System.out.println("userAuth.result=" + _userAuth__return);


        }
        {
        System.out.println("Invoking productServiceDetailQuery...");
        com.huawei.vas.bean.ProductServiceDetailQueryReq _productServiceDetailQuery_productServiceDetailQueryReq = null;
        com.huawei.vas.bean.ProductServiceDetailQueryResp _productServiceDetailQuery__return = port.productServiceDetailQuery(_productServiceDetailQuery_productServiceDetailQueryReq);
        System.out.println("productServiceDetailQuery.result=" + _productServiceDetailQuery__return);


        }
        {
        System.out.println("Invoking prodDetailQuery...");
        com.huawei.vas.bean.ProdDetailQueryReq _prodDetailQuery_prodDetailQueryReq = null;
        com.huawei.vas.bean.ProdDetailQueryResp _prodDetailQuery__return = port.prodDetailQuery(_prodDetailQuery_prodDetailQueryReq);
        System.out.println("prodDetailQuery.result=" + _prodDetailQuery__return);


        }
        {
        System.out.println("Invoking serviceDetailQuery...");
        com.huawei.vas.bean.ServiceDetailQueryReq _serviceDetailQuery_serviceDetailQueryReq = null;
        com.huawei.vas.bean.ServiceDetailQueryResp _serviceDetailQuery__return = port.serviceDetailQuery(_serviceDetailQuery_serviceDetailQueryReq);
        System.out.println("serviceDetailQuery.result=" + _serviceDetailQuery__return);


        }

        System.exit(0);
    }

}
